apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appConfigMap.name }}
  namespace: {{.Release.Namespace }}
  labels:
    {{- include "railsapp.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: "{{ .Values.appConfigMap.dbHost }}"
  RAILS_ENV: "{{ .Values.appConfigMap.environment }}"
