apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.appSecret.name }}
  labels:
    {{- include "railsapp.labels" . | nindent 4 }}
    namespace: {{ .Release.Namespace }}
data:
  POSTGRES_DB: dmlkZW9fZGV2ZWxvcG1lbnQ=
  POSTGRES_USER: cHJvZmVtenk=
  POSTGRES_PASSWORD: enVyaWVsODE=
  RAILS_MASTER_KEY: OGFmODE0YjNlMDhkOWUyNjNjNjYzNWYyMzFmYzU0MWY=