apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.appSecret.name }}
  labels:
    {{- include "railsapp.labels" . | nindent 4 }}
    namespace: {{ .Release.Namespace }}
data:
  POSTGRES_DB: cG9zdGdyZXM= # DEMO CREDS PLEASE  REPLACE
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: dFVvV0V3Z2hsYg==
  RAILS_MASTER_KEY: OGFmODE0YjNlMDhkOWUyNjNjNjYzNWYyMzFmYzU0MWY=