apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.appSecret.name }}
data:
  POSTGRES_DB: dmlkZW9fZGV2ZWxvcG1lbnQ=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: UXdScFR0a2lTYg==
  RAILS_MASTER_KEY: OGFmODE0YjNlMDhkOWUyNjNjNjYzNWYyMzFmYzU0MWY=